import type { Assignment } from "../_components/assignment-card";

export type AssignmentBase = Omit<Assignment, "rank">;

export const baseAssignments: AssignmentBase[] = [
  {
    id: 1,
    title: "Economics Problem Set",
    course: "ECO100",
    difficulty: "Medium",
    score: 38,
    due: "Oct 10, 2025",
    time: "2.5 hours",
    summary: "Supply and demand equilibrium analysis",
    yourGrade: "88%",
    classAverage: "82%",
  },
  {
    id: 2,
    title: "Calculus Integration Quiz",
    course: "MAT137",
    difficulty: "Hard",
    score: 42,
    due: "Oct 8, 2025",
    time: "1.5 hours",
    summary: "Advanced integration techniques and applications",
    yourGrade: "92%",
    classAverage: "78%",
  },
  {
    id: 3,
    title: "Python Data Structures Lab",
    course: "CSC148",
    difficulty: "Medium",
    score: 35,
    due: "Oct 12, 2025",
    time: "3 hours",
    summary: "Implement binary search trees and hash tables",
    yourGrade: "85%",
    classAverage: "80%",
  },
  {
    id: 4,
    title: "Chemistry Lab Report",
    course: "CHM135",
    difficulty: "Easy",
    score: 28,
    due: "Oct 15, 2025",
    time: "2 hours",
    summary: "Acid-base titration analysis and conclusions",
    yourGrade: "90%",
    classAverage: "86%",
  },
  {
    id: 5,
    title: "Literature Essay",
    course: "ENG200",
    difficulty: "Medium",
    score: 33,
    due: "Oct 14, 2025",
    time: "4 hours",
    summary: "Symbolism in modern American literature",
    yourGrade: "87%",
    classAverage: "83%",
  },
];
